
[mypy]
python_version = 3.10
ignore_missing_imports = True
files = src/lab1, tests/lab1, src/lab2, tests/lab2, src/lab3, tests/lab3, src/lab4, tests/lab4, src/sem2
exclude = ^(venv|\.venv|env|\.git|\.github|build|dist)/
namespace_packages = True
explicit_package_bases = True
